query pageQuery {
  ...LayoutQueryFragment
  projetsConnection {
    edges {
      node {
        id
        title
        mainImg {
          imgCentre {
            src
            alt
          }
        }
        type {
          ... on ProjetType {
            ...ProjetTypeParts
          }
        }
        _sys {
          filename
        }
      }
    }
  }
  servicesConnection {
    edges {
      node {
        id
        title
        seo {
          noindex
        }
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query projetQuery($relativePath: String!) {
  ...LayoutQueryFragment
  projets(relativePath: $relativePath) {
    ...ProjetsParts
    type {
      ... on ProjetType {
        name
      }
    }
  }
}

query serviceQuery($relativePath: String!) {
  ...LayoutQueryFragment
  services(relativePath: $relativePath) {
    ...ServicesParts
  }
}

query zoneQuery($relativePath: String!) {
  ...LayoutQueryFragment
  zones(relativePath: $relativePath) {
    ...ZonesParts
  }
}
